-- AlterTable
ALTER TABLE "Bill" ADD COLUMN     "total_cgst" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_sgst" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_vat" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "BillItem" ADD COLUMN     "cgst_amount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "cgst_rate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sgst_amount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sgst_rate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "vat_amount" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "vat_rate" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "vat_rate" DOUBLE PRECISION NOT NULL DEFAULT 0;
