export const AuditEvent = {
	PURCHASE_CREATE: "PURCHASE_CREATE",
	PURCHASE_DELETE: "PURCHASE_DELETE",
	BILL_CREATE: "BILL_CREATE",
	BILL_PAY: "BILL_PAY",
	BILL_CLOSE: "BILL_CLOSE",
	BILL_ROLLBACK: "BILL_ROLLBACK",
	BOTTLE_BREAK: "BOTTLE_BREAK",
	BOTTLE_FINISH: "BOTTLE_FINISH",
	KOT_CREATE: "KOT_CREATE",
	KOT_CANCEL: "KOT_CANCEL",
	KOT_SERVE: "KOT_SERVE",
	STOCK_ADJUST: "STOCK_ADJUST",
	USER_LOGIN: "USER_LOGIN",
	USER_LOGOUT: "USER_LOGOUT"
} as const;
